version: "3.7"
services:
  omdb-frontend-public:
    container_name: omdb-public
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_DOMAIN: ${API_DOMAIN}
    ports:
      - 4001:4001
